# -*- coding: utf-8 -*-
"""2nd_Order.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18T0YGMM8pcNqKq2tFHO6GeEgeaECHU6h
"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

# PINN neural network
class PINN(nn.Module):
    def __init__(self):
        super(PINN, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(1, 16),
            nn.Tanh(),
            nn.Linear(16, 32),
            nn.Tanh(),
            nn.Linear(32, 32),
            nn.Tanh(),
            nn.Linear(32, 16),
            nn.Tanh(),
            nn.Linear(16, 1)
        )

    def forward(self, x):
        return self.layers(x)

# Physics loss for: y'' + 16y = 0
def physics_loss(model, x):
    x.requires_grad = True
    u = model(x)

    u_x = torch.autograd.grad(u, x, torch.ones_like(u), create_graph=True)[0]
    u_xx = torch.autograd.grad(u_x, x, torch.ones_like(u_x), create_graph=True)[0]

    residual = u_xx + 16.0 * u
    return torch.mean(residual**2)

# Initial condition loss: y(0)=2, y'(0)=-2
def initial_loss(model):
    x0 = torch.tensor([[0.0]], requires_grad=True)

    u0 = model(x0)
    u0_x = torch.autograd.grad(u0, x0, torch.ones_like(u0), create_graph=True)[0]

    loss_u0 = (u0 - 2.0) ** 2
    loss_du0 = (u0_x + 2.0) ** 2   # y'(0) = -2

    return torch.mean(loss_u0 + loss_du0)

# Training
def train_pinn(model, optimizer, epochs=5000, num_train_points=256):
    physics_losses = []
    ic_losses = []
    total_losses = []

    for epoch in range(epochs):
        x = torch.rand(num_train_points, 1) * 2.0  # domain [0, 2]

        p_loss = physics_loss(model, x)
        i_loss = initial_loss(model)
        loss = p_loss + i_loss

        physics_losses.append(p_loss.item())
        ic_losses.append(i_loss.item())
        total_losses.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Loss: {loss.item():.6f}, "
                  f"Physics: {p_loss.item():.6f}, IC: {i_loss.item():.6f}")

    return physics_losses, ic_losses, total_losses

# Exact solution
def exact_solution(x):
    return 2*np.cos(4*x) - 0.5*np.sin(4*x)

# Main
if __name__ == "__main__":
    pinn_model = PINN()
    optimizer = torch.optim.Adam(pinn_model.parameters(), lr=5e-4)

    physics_losses, ic_losses, total_losses = train_pinn(
        pinn_model, optimizer, epochs=5000, num_train_points=256
    )

    # Test grid
    x_test = torch.linspace(0, 2, 200).reshape(-1, 1)
    u_pred = pinn_model(x_test).detach().numpy()

    # Plot PINN solution
    plt.figure()
    plt.plot(x_test.numpy(), u_pred, label="PINN Solution")
    plt.xlabel("x")
    plt.ylabel("y(x)")
    plt.title("PINN Solution")
    plt.legend()
    plt.show()

    # Separate plot for exact solution
    x_exact = np.linspace(0, 2, 400)
    y_exact = exact_solution(x_exact)

    plt.figure()
    plt.plot(x_exact, y_exact)
    plt.xlabel("x")
    plt.ylabel("y(x)")
    plt.title("Exact Solution")
    plt.show()